# Assignment 3

#### Task 1.1

In [6]:
def func(a,b):
    try:
        c=a/b
        return c
    except:
        return("Please avoid giving zero(0)")
        

In [7]:
d=func(3,0)
d

'Please avoid giving zero(0)'

#### Task 1.2

In [17]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for x in subjects:
    for y in verbs:
        for z in objects:
            print(x,y,z)



Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


#### Task 2.1

In [18]:
import numpy as np
def ATV_MTRX(inpt,n,increasing=False):
    if not increasing:
        output_mtrx=np.array([x**(n-1-i) for x in inpt for i in range(n)]).reshape(inpt.size,n)
    else:
        output_mtrx=np.array([x**i for x in inpt for i in range(n)]).reshape(inpt.size,n)
    return output_mtrx

In [19]:
inpt=np.array([1,2,3,4,5])
no_of_columns=3
ATV_MTRX_DECREASE=ATV_MTRX(inpt,no_of_columns,False)
ATV_MTRX_INCREASE=ATV_MTRX(inpt,no_of_columns,True)

print("*************OUTPUT SAMPLE1*****************\n")
print("The input array is:",inpt,"\n")
print("The no. of columns of the output ATV matrix is:",no_of_columns,"\n")
print("The ATV Matrix in decreasing order is:\n\n",ATV_MTRX_DECREASE,"\n")
print("The ATV Matrix in increasing order is:\n\n",ATV_MTRX_INCREASE,"\n")

*************OUTPUT SAMPLE1*****************

The input array is: [1 2 3 4 5] 

The no. of columns of the output ATV matrix is: 3 

The ATV Matrix in decreasing order is:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

The ATV Matrix in increasing order is:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

