In [1]:
import numpy as np

# Problem: Alexandre-Theophile Vandermonde matrix

In [13]:
def ATV_MTRX(inpt,n,increasing=False):
    if not increasing:
        output_mtrx=np.array([x**(n-1-i) for x in inpt for i in range(n)]).reshape(inpt.size,n)
    else:
        output_mtrx=np.array([x**i for x in inpt for i in range(n)]).reshape(inpt.size,n)
    return output_mtrx

In [19]:
inpt=np.array([1,2,3,4,5])
no_of_columns=3
ATV_MTRX_DECREASE=ATV_MTRX(inpt,no_of_columns,False)
ATV_MTRX_INCREASE=ATV_MTRX(inpt,no_of_columns,True)

print("*************OUTPUT SAMPLE1*****************\n")
print("The input array is:",inpt,"\n")
print("The no. of columns of the output ATV matrix is:",no_of_columns,"\n")
print("The ATV Matrix in decreasing order is:\n\n",ATV_MTRX_DECREASE,"\n")
print("The ATV Matrix in increasing order is:\n\n",ATV_MTRX_INCREASE,"\n")


inpt=np.array([1,3,5,7,9])
no_of_columns=4
ATV_MTRX_DECREASE=ATV_MTRX(inpt,no_of_columns,False)
ATV_MTRX_INCREASE=ATV_MTRX(inpt,no_of_columns,True)

print("*************OUTPUT SAMPLE2*****************\n")
print("The input array is:",inpt,"\n")
print("The no. of columns of the output ATV matrix is:",no_of_columns,"\n")
print("The ATV Matrix in decreasing order is:\n\n",ATV_MTRX_DECREASE,"\n")
print("The ATV Matrix in increasing order is:\n\n",ATV_MTRX_INCREASE,"\n")

*************OUTPUT SAMPLE1*****************

The input array is: [1 2 3 4 5] 

The no. of columns of the output ATV matrix is: 3 

The ATV Matrix in decreasing order is:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

The ATV Matrix in increasing order is:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

*************OUTPUT SAMPLE2*****************

The input array is: [1 3 5 7 9] 

The no. of columns of the output ATV matrix is: 4 

The ATV Matrix in decreasing order is:

 [[  1   1   1   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]] 

The ATV Matrix in increasing order is:

 [[  1   1   1   1]
 [  1   3   9  27]
 [  1   5  25 125]
 [  1   7  49 343]
 [  1   9  81 729]] 



# Problem No: 2

In [5]:
def mvng_avg(inpt,k):
    if k==0 or k>inpt.size:
        return("Please enter a value greater than 0 but less than length of the array")
    else:
        j=(inpt.size+1)-k
        output=np.array([int((np.sum(inpt[i:k+i],axis=0))/4) for i in range(j)])
    return output


In [6]:
inpt=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=int(input("Enter the window size for moving average: ")) #Window Size
output=mvng_avg(inpt,k)
print("\n*************Output Sample 1**************\n")
print("The input array is:\n",inpt,"\n")
print("The desired output is:\n",output)

Enter the window size for moving average: 3

*************Output Sample 1**************

The input array is:
 [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

The desired output is:
 [ 3  3  4  5  7 21 37 54 63 70 87]
